remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: POSSREL   
description:  A Data-Driven Generator of Design Possibility Distributions for Geotechnical Reliability Assessment
show_downloads: true
# google_analytics: [Your Google Analytics tracking ID]
github:
  zip_url: https://raw.githubusercontent.com/AntroxEV/POSSREL/main/PACKAGES/POSSREL.mlappinstall
  tar_url: http://example.com/download.zip
  another_url: another value
